### ISSUE TITLE
Model loading issue

### ISSUE THREAD

**Issue by ttharden** [luiscarlosgph/videosum#61]
Thank you very much for your work! Right now, I'm trying to reproduce your code and it's going smoothly for the part of selecting 'time' and getting the results. However,When using the 'inception', 'uid', and 'scda' methods, an error occurred while loading the model: _pickle.UnpicklingError: invalid load key, '<'.

**Comment by luiscarlosgph** [comment]
Hi @ttharden,


Could you please provide a minimal reproducible example and indicate the version of Python you are using?


Thank you,

Luis.

**Comment by ttharden** [comment]
**code:**python -m videosum.run --input data/video.mp4 --output data/uid.jpg --nframes 16 --height 1080 --width 1920 --algo uid --time-segmentation 1 

**version:**python==3.10 ubuntu==22.04

**Terminal running output message：**
/home/tkl/anaconda3/envs/videosum310/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/tkl/anaconda3/envs/videosum310/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/tkl/anaconda3/envs/videosum310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tkl/anaconda3/envs/videosum310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tkl/.local/lib/python3.10/site-packages/videosum/run.py", line 190, in <module>
    main()
  File "/home/tkl/.local/lib/python3.10/site-packages/videosum/run.py", line 151, in main
    im = vidsum.summarise(args.input)
  File "/home/tkl/.local/lib/python3.10/site-packages/videosum/videosum.py", line 254, in summarise
    key_frames = VideoSummariser.ALGOS[self.algo](self, input_path,
  File "/home/tkl/.local/lib/python3.10/site-packages/videosum/_methods/uid.py", line 41, in get_key_frames_uid
    model = videosum.InceptionFeatureExtractor('vector')
  File "/home/tkl/.local/lib/python3.10/site-packages/videosum/uid.py", line 61, in __init__
    self.model = videosum.InceptionV3().to(device)
  File "/home/tkl/.local/lib/python3.10/site-packages/videosum/inception.py", line 92, in __init__
    inception = fid_inception_v3()
  File "/home/tkl/.local/lib/python3.10/site-packages/videosum/inception.py", line 219, in fid_inception_v3
    state_dict = load_state_dict_from_url(FID_WEIGHTS_URL, progress=True)
  File "/home/tkl/anaconda3/envs/videosum310/lib/python3.10/site-packages/torch/hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/tkl/anaconda3/envs/videosum310/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/tkl/anaconda3/envs/videosum310/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by ttharden** [comment]
I apologize for any confusion caused.  Thank you@luiscarlosgph

**Comment by ttharden** [comment]
@luiscarlosgph  Thank you for your work! I have resolved this issue. Due to my network issue, the model file was not downloaded completely. I apologize for the inconvenience caused.

**Comment by luiscarlosgph** [comment]
No worries, @ttharden, glad everything works well now for you.
